# Generated by Django 5.2.14 on 2026-05-21 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Pagado')),
                ('uuid_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código Único')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='tickets/qr/', verbose_name='Código QR')),
                ('status', models.CharField(choices=[('ACTIVA', 'Activa'), ('UTILIZADA', 'Utilizada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=15, verbose_name='Estado de Entrada')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Compra')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
        ),
    ]
